### ISSUE TITLE
博客网站只能打开首页

### ISSUE THREAD

**Issue by 1732337191** [niumoo/JavaNotes#2]
https://www.wdbyte.com/
作者您好，看到您这个博客网站内容非常好，我搜藏时是正常的，今天只能打开首页，点进去报404

**Comment by niumoo** [comment]
可能昨天更新影响到了，我来处理下哈

**Comment by niumoo** [comment]
已处理，感谢支持哈。昨天更新内容格式的问题，网页没有构建成功。

**Comment by 1732337191** [comment]
谢谢
