### ISSUE TITLE
RSS feed 失效好久了

### ISSUE THREAD

**Issue by AiraNadih** [niumoo/JavaNotes#3]
以前有提供： `https://www.wdbyte.com/feed.atom`

**Comment by niumoo** [comment]
收到

**Comment by niumoo** [comment]
添加上了， [https://www.wdbyte.com/feed.xml](https://www.wdbyte.com/feed.xml)
之前是用的 vuepress ，插件已加就有了，现在网站是自己撸的，所有功能丢失了。

按照 feed atom rss 格式简单实现了一个，测试了下可以用。
<img width="1271" alt="image" src="https://github.com/niumoo/JavaNotes/assets/26371673/e894625a-2b16-4c36-bc09-5d1a697de4b2">
